name: Python Version File Scenarios

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  python-version-file-matrix:
    name: Setup Python from version file (${{ matrix.versionfile }}) on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        versionfile: 
          - '.python-version'
          - 'pyproject.toml'
          - '.tool-versions'
    steps:
      - uses: actions/checkout@v4
      - uses: timfel/setup-python@tim/graalpy-windows-ea
        with:
          python-version-file: ${{ matrix.versionfile }}
      - name: Run script
        run: python my_script.py
