name: Python Dependency Caching Scenarios

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  pipenv-cache:
    name: Cache pipenv dependencies (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: pipenv install

  poetry-cache:
    name: Cache poetry dependencies (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest

  pipenv-multi-lock-cache:
    name: Cache pipenv with multiple dependency files (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pipenv'
          cache-dependency-path: |
            server/app/Pipfile.lock
            __test__/app/Pipfile.lock
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: pipenv install

  pip-wildcard-cache:
    name: Cache pip with wildcard requirements-dev.txt (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: '**/requirements-dev.txt'
      - run: pip install -r src/dev/requirements-dev.txt

  pip-multi-wildcard-cache:
    name: Cache pip with multiple wildcard patterns (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            **/setup.cfg
            **/requirements*.txt
      - run: pip install -e . -r src/dev/requirements-dev.txt

  pip-setup-py-cache:
    name: Cache pip with setup.py (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: setup.py
      - run: pip install -e .
        # Or pip install -e '.[test]' to install test dependencies
